config/routes.rb
Rails.application.routes.draw do
  resources :carros
end

app/models/carro.rb
class Carro < ActiveRecord::Base

  has_attached_file :cover, :styles { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/default.png"
  
end                           

app/models/modelo.rb
class Modelo < ActiveRecord::Base  
  validates_presence_of :nome, :message => "O nome do carro deve ser preenchido."
  validates_presence_of :cor, :message => "A cor do carro deve ser preenchido."
  validates_presence_of :descricao, :message => "A descrição do carro deve ser preenchido."
  validates_presence_of :ano, :message => "O ano do carro deve ser preenchido."
  

  has_attached_file :cover, :styles { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: [:show, :edit, :update, :destroy]

  def index
    # instancia todos os carros
    @carros = Carro.all
 
    respond_to do |format|  
      # passando para o formato HTML
      format.html # index.html.erb
      # passando para o formato json
      format.json { render json: @carros }
      end
  end

  def show
     @carros = Carro.where(id: params[:id]).first
  end

  def new
    # instancia um novo carro
    @carros = Carro.new
  end

  def edit
    @carros = Carro.find(params[:id])
  end
  
  # metodo para criacao de carro
  def create
    # instanciando carro, passando o parametro carro_params
    @carro = Carro.new(carro_params)
    
    respond_to do |format|
      # se o parametro passado for dife
      if @carro.save
        # Redireciona para @carro, em formato html, com a mensagem (Carro cadastrado com sucesso!)
        format.html { redirect_to @carro, notice: 'Cadastrado com sucesso' }
        # Renderiza para @carro, em formato json
        format.json { render :show, status: :created, location: @carro }
      else
        # Faz um nova renderizacao em formato HTML
        format.html { render :new }
        # Renderiza para @carro ˜chamando˜ erro
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # metodo para atualizar
  def update  
    respond_to do |format|
      # Se o parametro passado for diferente 
      if @carro.update(carro_params)
        # Redireciona para @carro, em formato html, com a mensagem (carro atualizado com sucesso)
        format.html { redirect_to @carro, notice: 'Atualizado com sucesso.' }
        # Renderiza para @carro, em formato json
        format.json { render :show, status: :ok, location: @carro }
      else
        # Faz uma nova renderizacao em formato HTML
        format.html { render :edit }
        # Renderiza para @carro ˜chamando˜ erro
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # Metodo para remover 
  def destroy
    #passando o metodo destroy
    @carro.destroy
    respond_to do |format|
      # Redireciona para @carro, em formato html, com a mensagem (carro removido com suceso)
      format.html { redirect_to carros_url, notice: 'Deletado com sucesso.' }
      # formato json
      format.json { head :no_content }
    end
  end

  private
    def set_carro
      @carro = Carro.find(params[:id])
    end
    
    # metodo carro parametro
    def carro_params
      # passando os parametros do carro, que sao: nome, cor, descricao, ano
      params.require(:carro).permit(:nome, :cor, :descricao, :ano, :cover)
    end
end

app/controllers/index.rb
# GET /carros
# GET /carros.json
def index
  @carros = Contato.all
 
  respond_to do |format|
    format.html
    format.json { render json: @carros }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carro_helper.rb
module CarroHelper
 
  def hello
    "Carro!!"
  end
 
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/views/carros/_form.html.erb
<%= form_for(@carros, :html => { :multipart => true }) do |f| %>
  <% if @carros.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carro.errors.count, "error") %> Este carro está proibido de ser salvo: </h2>
      <ul>
      <% @carro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cor %><br>
    <%= f.text_field :cor %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.text_field :ano %>
  </div>
	
  <div class="field">
    <%= f.label :cover %><br>
    <%= f.file_field :cover %>
  </div>
	
	
	
	
	
  <div class="actions">
    <%= f.submit %>
  </div>
	
	
	<div class="field">
	<%= f.label :image %><br />
	<%= f.file_field :image %>
	</div>
<% end %>

app/views/carros/edit.html.erb
<h1>Edição/Alterar</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @carros %> |
<%= link_to 'Voltar', carros_path %>

app/views/carros/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Relatório</h1>

<table>	
	<%= image_tag @carros.cover.url(:thumb)%>
  <thead>
    <tr>
      <th class="text-center">Nome</th>
      <th class="text-center">Cor</th>
      <th class="text-center">Descrição</th>
      <th class="text-center">Ano</th>
    </tr>
  </thead>
  <tbody>
		<% @carros.each do |carro| %>
  	<tr>
    	<td scope="row" class="text-center"><%= carro.nome %></td> 
    	<td scope="row" class="text-center"><%= carro.cor %></td> 
    	<td scope="row" class="text-center"><%= carro.descricao %></td> 
			<td scope="row" class="text-center"><%= carro.ano %></td> 
			<td><%#= image_tag(carro.image.url(:thumb)) %></td>
      <td class="text-center">
    		<%= link_to 'Visualizar', carro %>
    		<%= link_to 'Excluir', { action: :destroy, id: carro.id }, method: :delete, data: { confirm: 'Confirma a exclusão do carro?' } %>				
        <%= link_to("Editar", edit_carro_path(carro.id), :class => 'action') %>
			</td>
  	</tr>
		<% end %>
	</tbody>
</table>
<br>

<%= link_to 'Novo Carro', new_carro_path %>

app/views/carros/new.html.erb
<h1>Cadastro/Novo</h1>

<%= render 'form' %>

<%= link_to 'Voltar', carros_path %>

app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @carro.nome %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @carro.cor %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @carro.descricao %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @carro.ano %>
</p>

<%= link_to 'Editar', edit_carro_path(@carro) %> |
<%= link_to 'Voltar', carros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeuCarro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>